### ISSUE TITLE
Add asserts for various scenarios in the Test Cases

### ISSUE THREAD

**Issue by sreev** [MarquezProject/marquez-python#107]
assert* are missing for Test Cases.

take a look at the tests/ folder.
eg. https://github.com/MarquezProject/marquez-python/blob/main/tests/test_marquez_wo_client.py
eg. https://github.com/MarquezProject/marquez-python/blob/main/tests/test_marquez_wo_client_http.py

**Comment by wslulciuc** [comment]
@sreev Mind adding a bit more details on the missing tests? It might be helpful to break them down by classes or link to code coverage reports.
