### ISSUE TITLE
MarquezClient has no _now_ms attribute

### ISSUE THREAD

**Issue by KrisB88** [MarquezProject/marquez-python#109]
When running the example usage in the README I get:

AttributeError: 'MarquezClient' object has no attribute '_now_ms'

It's coming from line 353 in client.py. It looks like the client should be using Utils.now_ms() instead of self._now_ms().  I'm happy to make this correction if that's the case.

**Comment by wslulciuc** [comment]
Thanks for opening this issue, @KrisB88! It looks like the `self._now_ms()` was removed. Sure, I'd be happy to approve the PR if you make the correction.

**Comment by KrisB88** [comment]
Does it make more sense to put the method in the client or just change the client code to use the Utils function?

**Comment by wslulciuc** [comment]
I would use the utils function. We originally had `_now_ms()` in the client class, but moved the function to `Utils` for reusability. Thanks for asking!

**Comment by KrisB88** [comment]
Awesome! I'll knock this out today!

**Comment by wslulciuc** [comment]
@KrisB88 Was wondering if you've been able to look into this issue? It'd be great to get a release out with your bug fix soon!

**Comment by KrisB88** [comment]
Yes the client code is complete! Tomorrow I need to write a test that confirms the fix. I assume mocking the object allows tests to pass so the plan is to write tests for the _get and _put methods and monkey patch the calls to the requests package. Does that sound like a reasonable plan?

**Comment by wslulciuc** [comment]
> I assume mocking the object allows tests to pass so the plan is to write tests for the _get and _put methods and monkey patch the calls to the requests package. Does that sound like a reasonable plan?

Yep, sounds like a solid approach to testing the fix 👍

**Comment by wslulciuc** [comment]
@KrisB88 Let us know if you need any guidance on how to test the fix :)

**Comment by KrisB88** [comment]
Working on it tonight! Sorry, I've been bogged down with work getting Marquez set up for us!

**Comment by KrisB88** [comment]
ok, it's not clear to me what I should do here for the tests. Using pytest to create a fixture as shown here (https://docs.pytest.org/en/stable/monkeypatch.html) can't be used inside a unittest.TestCase from what I can tell. Suggestions on how to swap out the calls to requests while keeping it inside the TestMarquezClient test case?

**Comment by wslulciuc** [comment]
@KrisB88 Thanks for taking the time to look into this issue (and sorry for the delayed response). Our test suites use [`unittest.mock`](https://docs.python.org/3/library/unittest.mock.html) for mocking. I was wondering if you've tried using that lib? (As an example usage, you can check out a test in another project [here](https://github.com/MarquezProject/marquez-airflow/blob/main/tests/test_marquez_dag.py)) Sorry for not clarifying this earlier.

This should help with mocking out the `requests` lib but also the response of the method calls.

**Comment by wslulciuc** [comment]
@KrisB88 Did you give `unittest.mock` for mocking a try?

**Comment by wslulciuc** [comment]
@KrisB88 I was wondering if you were able to write a test for the fix? Happy to answer any questions!

**Comment by wslulciuc** [comment]
@KrisB88: Thanks for looking into this issue, but given the client is currently broken, we need a hotfix release for the client. If there's another issue you'd like to pick up, please let us know!
