### ISSUE TITLE
Wrap API requests with try/catch

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez-python#56]
We'll want to wrap `requests.post`, `requests.put`, `requests.get` in a **try/catch** to handle `ConnectionErrors`, etc see [Errors and Exceptions](https://2.python-requests.org//en/latest/user/quickstart/#errors-and-exceptions) and define our own custom exceptions to handle network problem, timeouts, etc

see original discussion: https://github.com/MarquezProject/marquez-python/pull/52#discussion_r288640688

**Comment by ravikamaraj** [comment]
@wslulciuc , I can help with this task. thanks

**Comment by wslulciuc** [comment]
@ravikamaraj Was wondering if this was an issue you'd still like to work on?

**Comment by ravikamaraj** [comment]
@wslulciuc , I may not be able to contribute to this issue at this time. thanks for checking with me. Looking forward to contribute to your repos / products in near future. thanks

**Comment by wslulciuc** [comment]
No worries! Looking forward to future contributions :)
