### ISSUE TITLE
Fix support for limits and offsets for list_jobs and list_namespaces

### ISSUE THREAD

**Issue by alevine-wework** [MarquezProject/marquez-python#70]
Both offset and limit do not affect the output for list_jobs. Offset does not have an affect on the output of namespaces. Limit = 0 does not limit the namespaces outputted.
MarquezProject/marquez-python/client.py

**Comment by wslulciuc** [comment]
@alevine-wework Are you still seeing this issue when using  the `limit` and `offset` params?
