### ISSUE TITLE
Proposal: log events

### ISSUE THREAD

**Issue by sreev** [MarquezProject/marquez-python#88]
log events for various purposes including but not limited to debug and storage.

**current:**
uses py package logging

**proposal:**
enable log by default at INFO Level, enable file storage, rolling log file by size / no of files

**log content: (json type)**
log requests including headers, etc...
details required for debug ( order of http requests, etc... )
standardize across all marquez clients (python, java, etc...)

**environment variables:**
standardize on the environments variables used across each integration (Airflow, Spark, etc):
MARQUEZ_URL (default: http://localhost:8080)
MARQUEZ_NAMESPACE (required)
MARQUEZ_LOG_DIR (default: /var/log/marquez/client.requests.log)
MARQUEZ_LOG_REQUESTS_ENABLED (default: false)

**sample console log:**
```
>>> client.create_job_run("food_delivery", "my-job", None, None, run_args, False)
2020-08-18 13:56:47,762 | marquez_client | INFO | http://localhost:5000/api/v1/namespaces/food_delivery/jobs/my-job/runs duration_ms=27 method=POST payload={"runArgs": {"email": "me@mycorp.com", "emailOnFailure": "true", "emailOnRetry": "true", "retries": "1"}}

```

**Comment by wslulciuc** [comment]
Fixed #92
